---

- name: Disable empty password login
  notify: Restart sshd
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'

- name: Disable remote root login
  when: disable_root
  notify: Restart sshd
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Disable password login
  notify: Restart sshd
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Enable PubkeyAuthentication
  notify: Restart sshd
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PubkeyAuthentication '
    line: 'PubkeyAuthentication yes'

- name: Allow root login from local networks
  when: disable_root and allow_local_root
  notify: Restart sshd
  ansible.builtin.blockinfile:
    path: "{{ sshd_config }}"
    block: |
      Match Address 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        PermitRootLogin yes
        PasswordAuthentication yes
      Match All

- name: Suppress last login message
  notify: Restart sshd
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PrintLastLog '
    line: 'PrintLastLog no'
